//! Bundled `.ali` example files, embedded at compile time for the web GUI.
//!
//! Two uses:
//! - Listed in the frontend so users can pick an example to load.
//! - Seeded into the virtual loader so that `include <Name>` can resolve any
//!   bundled example by name, the same way it resolves files on disk in the CLI.
//!
//! The `EXAMPLES` list itself is generated by `build.rs` from the contents of
//! the `examples/` directory, so new files are picked up automatically on the
//! next build — no hand-editing required.

use std::collections::HashMap;

pub struct BundledExample {
    pub name: &'static str,
    pub content: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/bundled_examples.rs"));

/// Build a `<Name>.ali → content` map suitable for seeding a virtual [`Loader`].
pub fn virtual_module_files() -> HashMap<String, String> {
    EXAMPLES
        .iter()
        .map(|e| (format!("{}.ali", e.name), e.content.to_string()))
        .collect()
}

/// JSON array of `{ "name": ..., "content": ... }`.  Returned verbatim by both
/// the HTTP and WASM backends.
pub fn examples_json() -> String {
    let entries: Vec<serde_json::Value> = EXAMPLES
        .iter()
        .map(|e| serde_json::json!({ "name": e.name, "content": e.content }))
        .collect();
    serde_json::json!({ "status": "ok", "data": { "examples": entries } }).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_examples_are_nonempty() {
        assert!(!EXAMPLES.is_empty());
        for ex in EXAMPLES {
            assert!(!ex.content.is_empty(), "empty bundled example: {}", ex.name);
        }
    }
}
