//! Generates `bundled_examples.rs` (read via `include!` from `src/lib.rs`)
//! by enumerating every `*.ali` file in the workspace `examples/` directory.
//! Each entry becomes an `include_str!` call so the file contents end up in
//! the binary.  Cargo re-runs this script whenever `examples/` or its
//! contents change.

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // web/shared/ → workspace root → examples/
    let examples_dir = manifest_dir
        .join("..")
        .join("..")
        .join("examples")
        .canonicalize()
        .expect("examples/ must exist at the workspace root");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("bundled_examples.rs");

    println!("cargo:rerun-if-changed={}", examples_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&examples_dir) {
        for dirent in rd.flatten() {
            let path = dirent.path();
            if path.extension().and_then(|e| e.to_str()) != Some("ali") {
                continue;
            }
            let name = match path.file_stem().and_then(|s| s.to_str()) {
                Some(s) => s.to_owned(),
                None => continue,
            };
            let abs = path
                .canonicalize()
                .unwrap_or(path.clone())
                .to_string_lossy()
                .into_owned();
            println!("cargo:rerun-if-changed={}", abs);
            entries.push((name, abs));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Generated by build.rs — do not edit.\n");
    code.push_str("pub const EXAMPLES: &[BundledExample] = &[\n");
    for (name, abs) in &entries {
        // Escape backslashes for Windows paths; quotes in paths are not supported.
        let abs_escaped = abs.replace('\\', "\\\\");
        code.push_str(&format!(
            "    BundledExample {{ name: {:?}, content: include_str!(\"{}\") }},\n",
            name, abs_escaped,
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("write bundled_examples.rs");
}
