//! Cellular homology of a [`Complex`].
//!
//! Computes the chain complex of free abelian groups generated by the generators
//! of each dimension, with differentials defined by boundary face multiplicities,
//! then computes homology via Smith Normal Form.

use std::collections::HashMap;
use super::complex::Complex;

/// A finitely generated abelian group, represented as a free rank plus torsion invariants.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AbelianGroup {
    /// Rank of the free part (number of Z summands).
    pub free_rank: usize,
    /// Torsion invariants [d_1, d_2, ...] with 1 < d_1 | d_2 | ... | d_k.
    pub torsion: Vec<i64>,
}

/// A cycle in C_n witnessing a torsion class in H_n, along with the (n+1)-chain
/// whose boundary is `order · cycle`.
///
/// Invariant: `order · cycle = d_{n+1}(preimage)`, and `cycle` itself is not
/// in the image of `d_{n+1}`. Both chains are given in the original bases of
/// `C_n` and `C_{n+1}` respectively.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TorsionWitness {
    pub order: i64,
    pub cycle: Vec<(String, i64)>,
    pub preimage: Vec<(String, i64)>,
}

impl std::fmt::Display for TorsionWitness {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Z/{} cycle: {}", self.order, format_cycle(&self.cycle))?;
        if !self.preimage.is_empty() {
            write!(f, "  (preimage: {})", format_cycle(&self.preimage))?;
        }
        Ok(())
    }
}

fn format_cycle(cycle: &[(String, i64)]) -> String {
    if cycle.is_empty() { return "0".to_string(); }
    let mut out = String::new();
    for (i, (name, coeff)) in cycle.iter().enumerate() {
        let abs = coeff.abs();
        let sign = if *coeff < 0 { "-" } else if i == 0 { "" } else { "+" };
        if i == 0 {
            if abs == 1 { out.push_str(&format!("{}{}", sign, name)); }
            else { out.push_str(&format!("{}{}·{}", sign, abs, name)); }
        } else {
            out.push(' ');
            if abs == 1 { out.push_str(&format!("{} {}", sign, name)); }
            else { out.push_str(&format!("{} {}·{}", sign, abs, name)); }
        }
    }
    out
}

impl std::fmt::Display for AbelianGroup {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut parts = Vec::new();
        if self.free_rank > 0 {
            if self.free_rank == 1 {
                parts.push("Z".to_string());
            } else {
                parts.push(format!("Z^{}", self.free_rank));
            }
        }
        for &d in &self.torsion {
            parts.push(format!("Z/{}", d));
        }
        if parts.is_empty() {
            write!(f, "0")
        } else {
            write!(f, "{}", parts.join(" + "))
        }
    }
}

/// The cellular homology of a complex, indexed by dimension.
#[derive(Debug)]
pub struct Homology {
    /// H_n for each dimension n that has generators.
    pub groups: Vec<(usize, AbelianGroup)>,
    /// Euler characteristic: Σ (-1)^n |C_n|.
    pub euler_characteristic: i64,
    /// For each dimension n, cycles in C_n witnessing the torsion classes of H_n.
    pub torsion_witnesses: HashMap<usize, Vec<TorsionWitness>>,
}

impl Homology {
    /// Euler characteristic computed from the homology groups (should equal
    /// the one computed from the chain complex ranks).
    pub fn euler_from_homology(&self) -> i64 {
        self.groups.iter().map(|(n, g)| {
            let rank = g.free_rank as i64;
            if n % 2 == 0 { rank } else { -rank }
        }).sum()
    }
}

impl std::fmt::Display for Homology {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (dim, group) in &self.groups {
            writeln!(f, "H_{} = {}", dim, group)?;
            if let Some(witnesses) = self.torsion_witnesses.get(dim) {
                for w in witnesses {
                    writeln!(f, "    {}", w)?;
                }
            }
        }
        writeln!(f, "χ = {}", self.euler_characteristic)?;
        Ok(())
    }
}

/// Compute the cellular homology of a complex.
///
/// The chain complex C_n is free on the n-dimensional generators.
/// The differential d_n: C_n → C_{n-1} sends generator g to
/// (sum of output (n-1)-faces) - (sum of input (n-1)-faces),
/// counted with multiplicity.
pub fn compute_homology(complex: &Complex) -> Homology {
    // Collect generators by dimension, with stable ordering.
    let mut gens_by_dim: HashMap<usize, Vec<String>> = HashMap::new();
    for (name, _, dim) in complex.generators_iter() {
        gens_by_dim.entry(dim).or_default().push(name.clone());
    }
    // Sort within each dimension for deterministic ordering.
    for v in gens_by_dim.values_mut() {
        v.sort();
    }

    if gens_by_dim.is_empty() {
        return Homology {
            groups: vec![],
            euler_characteristic: 0,
            torsion_witnesses: HashMap::new(),
        };
    }


    let max_dim = *gens_by_dim.keys().max().unwrap();

    // Build differential matrices.
    // diff[n] is the matrix for d_n: C_n → C_{n-1}.
    // Rows indexed by (n-1)-generators, columns by n-generators.
    let mut differentials: HashMap<usize, Vec<Vec<i64>>> = HashMap::new();

    for n in 1..=max_dim {
        let Some(cols) = gens_by_dim.get(&n) else { continue; };
        let Some(rows) = gens_by_dim.get(&(n - 1)) else { continue; };
        if cols.is_empty() || rows.is_empty() { continue; }

        // Map (n-1)-generator names to row indices.
        let row_index: HashMap<&str, usize> = rows.iter()
            .enumerate()
            .map(|(i, name)| (name.as_str(), i))
            .collect();

        let num_rows = rows.len();
        let num_cols = cols.len();

        let mut matrix = vec![vec![0i64; num_cols]; num_rows];

        for (col, gen_name) in cols.iter().enumerate() {
            let Some(classifier) = complex.classifier(gen_name) else { continue; };
            let d = classifier.top_dim();
            if d < 1 { continue; }

            // The classifier has a single top-dimensional cell at position 0.
            // Read its output and input faces directly from the ogposet.
            let labels_below = classifier.labels_at(d - 1);

            // Output faces: +1 for each occurrence.
            for &face_pos in &classifier.shape.faces_of(
                super::ogposet::Sign::Output, d, 0,
            ) {
                if let Some(tag) = labels_below.and_then(|ls| ls.get(face_pos)) {
                    if let Some(name) = complex.find_generator_by_tag(tag) {
                        if let Some(&row) = row_index.get(name.as_str()) {
                            matrix[row][col] += 1;
                        }
                    }
                }
            }

            // Input faces: -1 for each occurrence.
            for &face_pos in &classifier.shape.faces_of(
                super::ogposet::Sign::Input, d, 0,
            ) {
                if let Some(tag) = labels_below.and_then(|ls| ls.get(face_pos)) {
                    if let Some(name) = complex.find_generator_by_tag(tag) {
                        if let Some(&row) = row_index.get(name.as_str()) {
                            matrix[row][col] -= 1;
                        }
                    }
                }
            }
        }

        differentials.insert(n, matrix);
    }

    // Sanity check: d_n ∘ d_{n+1} = 0 for all n.
    for n in 2..=max_dim {
        if let (Some(dn), Some(dn1)) = (differentials.get(&n), differentials.get(&(n - 1))) {
            // dn1 is (n-2)×(n-1), dn is (n-1)×n. Product dn1 * dn should be zero.
            // Actually: d_{n-1} ∘ d_n, i.e. multiply d_{n-1} (rows=n-2 gens, cols=n-1 gens)
            // by d_n (rows=n-1 gens, cols=n gens).
            // But differentials[n] has rows indexed by (n-1)-gens, cols by n-gens.
            // differentials[n-1] has rows indexed by (n-2)-gens, cols by (n-1)-gens.
            // Product: differentials[n-1] * differentials[n] should be zero.
            let product = mat_mul(dn1, dn);
            debug_assert!(
                product.iter().all(|row| row.iter().all(|&v| v == 0)),
                "d² ≠ 0 at dimension {}: d_{} ∘ d_{} is nonzero",
                n, n - 1, n,
            );
        }
    }

    // Compute homology at each dimension.
    let mut groups = Vec::new();
    let mut torsion_witnesses: HashMap<usize, Vec<TorsionWitness>> = HashMap::new();
    let mut dims: Vec<usize> = gens_by_dim.keys().copied().collect();
    dims.sort();

    for &n in &dims {
        let num_gens = gens_by_dim[&n].len();

        // d_n: C_n → C_{n-1}  (may not exist if n=0 or no (n-1)-generators)
        let rank_dn = differentials.get(&n)
            .map(|m| matrix_rank(m))
            .unwrap_or(0);

        // d_{n+1}: C_{n+1} → C_n  (may not exist)
        // We compute SNF with basis tracking and then apply the canonical
        // normalisations (enforce_divisibility, sort) to BOTH diag and u_inv.
        // This keeps torsion witnesses paired with the reported invariants
        // even when enforce_divisibility mixes pairs (e.g. raw [2, 3] → canonical [1, 6]).
        let snf_dn1 = differentials.get(&(n + 1))
            .map(|m| smith_normal_form_with_basis(m));

        let (rank_dn1, torsion, witnesses) = match snf_dn1 {
            Some((mut diag, mut u_inv, mut v)) => {
                enforce_divisibility_tracked(&mut diag, &mut u_inv, &mut v);
                sort_diag_tracked(&mut diag, &mut u_inv, &mut v);

                let n_gens = &gens_by_dim[&n];
                let empty = Vec::new();
                let n1_gens: &Vec<String> = gens_by_dim.get(&(n + 1)).unwrap_or(&empty);

                let ws: Vec<TorsionWitness> = diag.iter().enumerate()
                    .filter(|&(_, &d)| d > 1)
                    .map(|(col, &d)| {
                        let mut cycle: Vec<(String, i64)> = n_gens.iter().enumerate()
                            .filter_map(|(row, name)| {
                                let c = u_inv.get(row).and_then(|r| r.get(col)).copied().unwrap_or(0);
                                if c != 0 { Some((name.clone(), c)) } else { None }
                            })
                            .collect();
                        let mut preimage: Vec<(String, i64)> = n1_gens.iter().enumerate()
                            .filter_map(|(row, name)| {
                                let c = v.get(row).and_then(|r| r.get(col)).copied().unwrap_or(0);
                                if c != 0 { Some((name.clone(), c)) } else { None }
                            })
                            .collect();
                        // ±(z, p) both witness the same class — prefer cycle leading positive.
                        if cycle.first().is_some_and(|(_, c)| *c < 0) {
                            for (_, c) in cycle.iter_mut() { *c = -*c; }
                            for (_, c) in preimage.iter_mut() { *c = -*c; }
                        }
                        TorsionWitness { order: d, cycle, preimage }
                    })
                    .collect();

                let rank = diag.iter().filter(|&&d| d != 0).count();
                let torsion: Vec<i64> = diag.iter()
                    .filter(|&&d| d > 1)
                    .copied()
                    .collect();
                (rank, torsion, ws)
            }
            None => (0, vec![], vec![]),
        };

        let free_rank = num_gens - rank_dn - rank_dn1;
        if !witnesses.is_empty() {
            torsion_witnesses.insert(n, witnesses);
        }
        groups.push((n, AbelianGroup { free_rank, torsion }));
    }

    // Euler characteristic: Σ (-1)^n |C_n|.
    let euler_characteristic: i64 = gens_by_dim.iter().map(|(&n, v)| {
        let count = v.len() as i64;
        if n % 2 == 0 { count } else { -count }
    }).sum();

    let result = Homology { groups, euler_characteristic, torsion_witnesses };
    debug_assert_eq!(
        result.euler_characteristic, result.euler_from_homology(),
        "Euler characteristic mismatch: chain complex gives {}, homology gives {}",
        result.euler_characteristic, result.euler_from_homology(),
    );
    result
}

/// Multiply two integer matrices.
fn mat_mul(a: &[Vec<i64>], b: &[Vec<i64>]) -> Vec<Vec<i64>> {
    let rows_a = a.len();
    let cols_b = if b.is_empty() { 0 } else { b[0].len() };
    let inner = if a.is_empty() { 0 } else { a[0].len() };
    let mut c = vec![vec![0i64; cols_b]; rows_a];
    for i in 0..rows_a {
        for k in 0..inner {
            if a[i][k] == 0 { continue; }
            for j in 0..cols_b {
                c[i][j] += a[i][k] * b[k][j];
            }
        }
    }
    c
}

// ── Smith Normal Form ────────────────────────────────────────────────────────

/// Compute the Smith Normal Form diagonal of an integer matrix.
///
/// Returns the diagonal entries [d_1, d_2, ...] with d_i | d_{i+1},
/// sorted so that zero entries come last.
fn smith_normal_form(matrix: &[Vec<i64>]) -> Vec<i64> {
    if matrix.is_empty() { return vec![]; }
    let num_rows = matrix.len();
    let num_cols = matrix[0].len();
    if num_cols == 0 { return vec![]; }

    // Work on a mutable copy.
    let mut m: Vec<Vec<i64>> = matrix.to_vec();

    let min_dim = num_rows.min(num_cols);
    let mut pivot = 0;

    while pivot < min_dim {
        // Find a nonzero entry in the submatrix m[pivot..][pivot..].
        if !find_and_move_pivot(&mut m, pivot, num_rows, num_cols) {
            break; // remaining submatrix is zero
        }

        // Eliminate entries in the pivot row and column.
        // After eliminating, check if the pivot divides all entries in the
        // remaining submatrix. If not, add a non-divisible entry's row to
        // the pivot row and repeat. The pivot value strictly decreases each
        // time a GCD reduction occurs, guaranteeing termination.
        loop {
            // Phase 1: zero out pivot column and row.
            loop {
                eliminate_column(&mut m, pivot, num_rows);
                eliminate_row(&mut m, pivot, num_cols);
                if is_pivot_clean(&m, pivot, num_rows, num_cols) { break; }
            }
            // Phase 2: check divisibility in the remaining submatrix.
            let pv = m[pivot][pivot];
            if pv == 0 { break; }
            let mut found_bad = false;
            'search: for r in (pivot + 1)..num_rows {
                for c in (pivot + 1)..num_cols {
                    if m[r][c] % pv != 0 {
                        // Add row r to pivot row to introduce a non-divisible entry,
                        // which will reduce the pivot via GCD on the next iteration.
                        for j in 0..num_cols {
                            m[pivot][j] += m[r][j];
                        }
                        found_bad = true;
                        break 'search;
                    }
                }
            }
            if !found_bad { break; }
        }

        // Ensure the pivot is positive.
        if m[pivot][pivot] < 0 {
            for j in 0..num_cols { m[pivot][j] = -m[pivot][j]; }
        }

        pivot += 1;
    }

    // Extract diagonal and enforce divisibility.
    let mut diag: Vec<i64> = (0..min_dim).map(|i| m[i][i].abs()).collect();
    enforce_divisibility(&mut diag);

    // Sort: nonzero first (in divisibility order), then zeros.
    diag.sort_by(|a, b| {
        match (a == &0, b == &0) {
            (true, false) => std::cmp::Ordering::Greater,
            (false, true) => std::cmp::Ordering::Less,
            _ => a.cmp(b),
        }
    });

    diag
}

/// Compute the rank of an integer matrix (number of nonzero rows in its row echelon form).
fn matrix_rank(matrix: &[Vec<i64>]) -> usize {
    // Use Smith form — rank = number of nonzero diagonal entries.
    smith_normal_form(matrix).iter().filter(|&&d| d != 0).count()
}

// ── SNF with change-of-basis tracking ────────────────────────────────────────

/// Compute Smith Normal Form, along with change-of-basis matrices for both
/// the row and column spaces.
///
/// Returns `(diag, u_inv, v)` where, after SNF, `U · M · V = diag(…)`:
/// - Column `i` of `u_inv` is the `i`-th new basis element of the row space
///   (C_n) expressed in the original basis. If `diag[i] > 1`, it is a torsion
///   witness cycle.
/// - Column `i` of `v` is the `i`-th new basis element of the column space
///   (C_{n+1}) expressed in the original basis. For a torsion diagonal entry
///   `diag[i] = d`, `d_{n+1}(column_i(v)) = d · column_i(u_inv)`.
///
/// The returned `diag` is in *raw* (pre-normalisation) order, paired
/// positionally with the columns of `u_inv` and `v`.
fn smith_normal_form_with_basis(matrix: &[Vec<i64>]) -> (Vec<i64>, Vec<Vec<i64>>, Vec<Vec<i64>>) {
    let num_rows = matrix.len();
    if num_rows == 0 { return (vec![], vec![], vec![]); }
    let num_cols = matrix[0].len();
    if num_cols == 0 { return (vec![], identity(num_rows), vec![]); }

    let mut m: Vec<Vec<i64>> = matrix.to_vec();
    let mut u_inv: Vec<Vec<i64>> = identity(num_rows);
    let mut v: Vec<Vec<i64>> = identity(num_cols);

    let min_dim = num_rows.min(num_cols);
    let mut pivot = 0;

    while pivot < min_dim {
        if !find_and_move_pivot_tracked(&mut m, &mut u_inv, &mut v, pivot, num_rows, num_cols) {
            break;
        }
        loop {
            loop {
                eliminate_column_tracked(&mut m, &mut u_inv, pivot, num_rows);
                eliminate_row_tracked(&mut m, &mut v, pivot, num_cols);
                if is_pivot_clean(&m, pivot, num_rows, num_cols) { break; }
            }
            let pv = m[pivot][pivot];
            if pv == 0 { break; }
            let mut found_bad = false;
            'search: for r in (pivot + 1)..num_rows {
                for c in (pivot + 1)..num_cols {
                    if m[r][c] % pv != 0 {
                        row_add_tracked(&mut m, &mut u_inv, pivot, r, 1);
                        found_bad = true;
                        break 'search;
                    }
                }
            }
            if !found_bad { break; }
        }

        if m[pivot][pivot] < 0 {
            row_negate_tracked(&mut m, &mut u_inv, pivot);
        }

        pivot += 1;
    }

    let diag: Vec<i64> = (0..min_dim).map(|i| m[i][i]).collect();
    (diag, u_inv, v)
}

fn identity(n: usize) -> Vec<Vec<i64>> {
    (0..n).map(|i| (0..n).map(|j| if i == j { 1 } else { 0 }).collect()).collect()
}

/// Row swap on `m` with corresponding column swap on `u_inv`.
///
/// A row op E applied to M also acts on U (U := E·U). The corresponding action
/// on U^{-1} (so that U·U^{-1} stays the identity) is right-multiplication by
/// E^{-1}. For a row swap (self-inverse), that's a column swap on U_inv.
fn row_swap_tracked(m: &mut [Vec<i64>], u_inv: &mut [Vec<i64>], p: usize, r: usize) {
    m.swap(p, r);
    for row in u_inv.iter_mut() {
        row.swap(p, r);
    }
}

/// `R_dest += q · R_src` on `m`, with the inverse column op `C_src -= q · C_dest` on `u_inv`.
fn row_add_tracked(m: &mut [Vec<i64>], u_inv: &mut [Vec<i64>], dest: usize, src: usize, q: i64) {
    let ncols = m[0].len();
    for j in 0..ncols {
        m[dest][j] += q * m[src][j];
    }
    for row in u_inv.iter_mut() {
        let cd = row[dest];
        row[src] -= q * cd;
    }
}

/// Negate row `r` on `m`, with the corresponding column negation on `u_inv`.
fn row_negate_tracked(m: &mut [Vec<i64>], u_inv: &mut [Vec<i64>], r: usize) {
    let ncols = m[0].len();
    for j in 0..ncols { m[r][j] = -m[r][j]; }
    for row in u_inv.iter_mut() { row[r] = -row[r]; }
}

/// 2×2 GCD-style row op replacing `(R_p, R_r)` with `(s·R_p + t·R_r, -b·R_p + a·R_r)`.
/// The inverse column op on `u_inv` is the 2×2 block `[[a, -t], [b, s]]` on cols `(p, r)`.
fn row_gcd_tracked(
    m: &mut [Vec<i64>], u_inv: &mut [Vec<i64>],
    p: usize, r: usize,
    s: i64, t: i64, a: i64, b: i64,
) {
    let ncols = m[0].len();
    let old_p = m[p].clone();
    let old_r = m[r].clone();
    for j in 0..ncols {
        m[p][j] = s * old_p[j] + t * old_r[j];
        m[r][j] = -b * old_p[j] + a * old_r[j];
    }
    for row in u_inv.iter_mut() {
        let cp = row[p];
        let cr = row[r];
        row[p] = a * cp + b * cr;
        row[r] = -t * cp + s * cr;
    }
}

/// Like `find_and_move_pivot` but mirrors the row swap onto `u_inv` and the
/// column swap onto `v`.
fn find_and_move_pivot_tracked(
    m: &mut [Vec<i64>], u_inv: &mut [Vec<i64>], v: &mut [Vec<i64>],
    pivot: usize, nrows: usize, ncols: usize,
) -> bool {
    let mut best: Option<(usize, usize, i64)> = None;
    for r in pivot..nrows {
        for c in pivot..ncols {
            let val = m[r][c].abs();
            if val > 0 {
                if best.is_none() || val < best.unwrap().2 {
                    best = Some((r, c, val));
                }
            }
        }
    }
    let Some((br, bc, _)) = best else { return false; };
    if br != pivot {
        row_swap_tracked(m, u_inv, pivot, br);
    }
    if bc != pivot {
        for row in m.iter_mut() { row.swap(pivot, bc); }
        for row in v.iter_mut() { row.swap(pivot, bc); }
    }
    true
}

/// Like `eliminate_row` but mirrors the column ops onto `v`.
fn eliminate_row_tracked(m: &mut [Vec<i64>], v: &mut [Vec<i64>], pivot: usize, ncols: usize) {
    let nrows = m.len();
    let pv = m[pivot][pivot];
    for c in (pivot + 1)..ncols {
        if m[pivot][c] == 0 { continue; }
        if pv != 0 && m[pivot][c] % pv == 0 {
            let q = m[pivot][c] / pv;
            // C_c -= q · C_pivot on both m and v.
            for r in 0..nrows { m[r][c] -= q * m[r][pivot]; }
            for row in v.iter_mut() { row[c] -= q * row[pivot]; }
        } else {
            let (g, s, t) = extended_gcd(pv, m[pivot][c]);
            let a = pv / g;
            let b = m[pivot][c] / g;
            // 2×2 column op on cols (pivot, c): new_pivot = s·old_pivot + t·old_c,
            // new_c = -b·old_pivot + a·old_c. Apply to m and to v.
            for r in 0..nrows {
                let o1 = m[r][pivot];
                let o2 = m[r][c];
                m[r][pivot] = s * o1 + t * o2;
                m[r][c] = -b * o1 + a * o2;
            }
            for row in v.iter_mut() {
                let o1 = row[pivot];
                let o2 = row[c];
                row[pivot] = s * o1 + t * o2;
                row[c] = -b * o1 + a * o2;
            }
        }
    }
}

/// Like `enforce_divisibility` but tracks `u_inv` so that, for every adjacent pair
/// `(a, b)` with `a ∤ b` that is collapsed to `(gcd(a, b), lcm(a, b))`, the
/// corresponding pair of columns of `u_inv` is updated to remain a valid witness
/// basis for the new diagonal entries.
///
/// The underlying matrix-level operations collapsing the 2×2 block
/// `[[a, 0], [0, b]]` to `[[g, 0], [0, l]]` (where `g = gcd`, `l = lcm`) are:
///   - row op `R_i += R_{i+1}` (→ on `u_inv`, `C_{i+1} -= C_i`),
///   - one column op on the block (does not affect `u_inv`),
///   - row op `R_{i+1} -= (b·t/g)·R_i` where `t` is the Bézout coefficient of `b`
///     in `g = s·a + t·b` (→ on `u_inv`, `C_i += (b·t/g)·C_{i+1}`).
fn enforce_divisibility_tracked(
    diag: &mut Vec<i64>,
    u_inv: &mut [Vec<i64>],
    v: &mut [Vec<i64>],
) {
    let n = diag.len();
    let mut changed = true;
    while changed {
        changed = false;
        for i in 0..n.saturating_sub(1) {
            if diag[i] == 0 || diag[i + 1] == 0 { continue; }
            let a = diag[i];
            let b = diag[i + 1];
            if b % a == 0 { continue; }

            let (g, s, t) = extended_gcd(a, b);
            let l = a / g * b;
            let q = b * t / g;
            let a_g = a / g;
            let b_g = b / g;

            // Op 1 on u_inv: C_{i+1} -= C_i.
            for row in u_inv.iter_mut() {
                let ci = row[i];
                row[i + 1] -= ci;
            }
            // Op 2 is a column op on M with 2×2 block [[s, -b_g], [t, a_g]]
            // on cols (i, i+1); mirror on v.
            for row in v.iter_mut() {
                let oi = row[i];
                let oi1 = row[i + 1];
                row[i] = s * oi + t * oi1;
                row[i + 1] = -b_g * oi + a_g * oi1;
            }
            // Op 3 on u_inv: C_i += q · C_{i+1}  (uses the already-updated C_{i+1}).
            for row in u_inv.iter_mut() {
                let ci1 = row[i + 1];
                row[i] += q * ci1;
            }

            diag[i] = g;
            diag[i + 1] = l;
            changed = true;
        }
    }
}

/// Sort `diag` so zeros come last and nonzero entries are in increasing order,
/// permuting the corresponding columns of `u_inv` and `v` in lockstep.
/// Swapping diagonal positions `i, j` corresponds to both a row swap (→ col
/// swap on `u_inv`) and a column swap (→ col swap on `v`) on the SNF matrix.
fn sort_diag_tracked(
    diag: &mut Vec<i64>,
    u_inv: &mut [Vec<i64>],
    v: &mut [Vec<i64>],
) {
    let n = diag.len();
    if n == 0 { return; }
    let mut perm: Vec<usize> = (0..n).collect();
    perm.sort_by(|&a, &b| {
        match (diag[a] == 0, diag[b] == 0) {
            (true, false) => std::cmp::Ordering::Greater,
            (false, true) => std::cmp::Ordering::Less,
            _ => diag[a].cmp(&diag[b]),
        }
    });
    let new_diag: Vec<i64> = perm.iter().map(|&i| diag[i]).collect();
    permute_first_n_columns(u_inv, &perm, n);
    permute_first_n_columns(v, &perm, n);
    *diag = new_diag;
}

fn permute_first_n_columns(mat: &mut [Vec<i64>], perm: &[usize], n: usize) {
    for row in mat.iter_mut() {
        let ncols = row.len();
        let new_row: Vec<i64> = (0..ncols)
            .map(|c| if c < n { row[perm[c]] } else { row[c] })
            .collect();
        *row = new_row;
    }
}

/// Like `eliminate_column` but mirrors row ops onto `u_inv`.
fn eliminate_column_tracked(m: &mut [Vec<i64>], u_inv: &mut [Vec<i64>], pivot: usize, nrows: usize) {
    let pv = m[pivot][pivot];
    for r in (pivot + 1)..nrows {
        if m[r][pivot] == 0 { continue; }
        if pv != 0 && m[r][pivot] % pv == 0 {
            let q = m[r][pivot] / pv;
            // R_r -= q · R_pivot, i.e. R_r += (-q) · R_pivot.
            row_add_tracked(m, u_inv, r, pivot, -q);
        } else {
            let (g, s, t) = extended_gcd(pv, m[r][pivot]);
            let a = pv / g;
            let b = m[r][pivot] / g;
            row_gcd_tracked(m, u_inv, pivot, r, s, t, a, b);
        }
    }
}

/// Find a nonzero entry in m[pivot..][pivot..] and swap it to (pivot, pivot).
fn find_and_move_pivot(m: &mut [Vec<i64>], pivot: usize, nrows: usize, ncols: usize) -> bool {
    // Prefer the smallest nonzero absolute value for better elimination.
    let mut best: Option<(usize, usize, i64)> = None;
    for r in pivot..nrows {
        for c in pivot..ncols {
            let v = m[r][c].abs();
            if v > 0 {
                if best.is_none() || v < best.unwrap().2 {
                    best = Some((r, c, v));
                }
            }
        }
    }
    let Some((br, bc, _)) = best else { return false; };
    m.swap(pivot, br);
    for row in m.iter_mut() {
        row.swap(pivot, bc);
    }
    true
}

/// Eliminate entries in the pivot column below the pivot using row operations.
///
/// Uses simple subtraction when the pivot divides the entry (avoids changing
/// the pivot row). Falls back to GCD-based operations when it doesn't.
fn eliminate_column(m: &mut [Vec<i64>], pivot: usize, nrows: usize) {
    let ncols = m[0].len();
    let pv = m[pivot][pivot];
    for r in (pivot + 1)..nrows {
        if m[r][pivot] == 0 { continue; }
        if pv != 0 && m[r][pivot] % pv == 0 {
            // Simple case: subtract a multiple of the pivot row.
            let q = m[r][pivot] / pv;
            for j in 0..ncols {
                m[r][j] -= q * m[pivot][j];
            }
        } else {
            // GCD case: replace pivot with gcd.
            let (g, s, t) = extended_gcd(pv, m[r][pivot]);
            let a = pv / g;
            let b = m[r][pivot] / g;
            let old_pivot_row = m[pivot].clone();
            let old_r_row = m[r].clone();
            for j in 0..ncols {
                m[pivot][j] = s * old_pivot_row[j] + t * old_r_row[j];
                m[r][j] = -b * old_pivot_row[j] + a * old_r_row[j];
            }
        }
    }
}

/// Eliminate entries in the pivot row to the right of the pivot using column operations.
///
/// Uses simple subtraction when the pivot divides the entry. Falls back to
/// GCD-based operations when it doesn't.
fn eliminate_row(m: &mut [Vec<i64>], pivot: usize, ncols: usize) {
    let nrows = m.len();
    let pv = m[pivot][pivot];
    for c in (pivot + 1)..ncols {
        if m[pivot][c] == 0 { continue; }
        if pv != 0 && m[pivot][c] % pv == 0 {
            let q = m[pivot][c] / pv;
            for r in 0..nrows {
                m[r][c] -= q * m[r][pivot];
            }
        } else {
            let (g, s, t) = extended_gcd(pv, m[pivot][c]);
            let a = pv / g;
            let b = m[pivot][c] / g;
            let old_pivot_col: Vec<i64> = (0..nrows).map(|r| m[r][pivot]).collect();
            let old_c_col: Vec<i64> = (0..nrows).map(|r| m[r][c]).collect();
            for r in 0..nrows {
                m[r][pivot] = s * old_pivot_col[r] + t * old_c_col[r];
                m[r][c] = -b * old_pivot_col[r] + a * old_c_col[r];
            }
        }
    }
}

/// Check if all entries in the pivot's row and column (outside the pivot) are zero.
fn is_pivot_clean(m: &[Vec<i64>], pivot: usize, nrows: usize, ncols: usize) -> bool {
    for r in (pivot + 1)..nrows {
        if m[r][pivot] != 0 { return false; }
    }
    for c in (pivot + 1)..ncols {
        if m[pivot][c] != 0 { return false; }
    }
    true
}

/// Enforce the divisibility condition d_i | d_{i+1} on the diagonal.
fn enforce_divisibility(diag: &mut Vec<i64>) {
    let n = diag.len();
    let mut changed = true;
    while changed {
        changed = false;
        for i in 0..n.saturating_sub(1) {
            if diag[i] == 0 || diag[i + 1] == 0 { continue; }
            if diag[i + 1] % diag[i] != 0 {
                let g = gcd(diag[i], diag[i + 1]);
                let l = diag[i] / g * diag[i + 1]; // lcm
                diag[i] = g;
                diag[i + 1] = l;
                changed = true;
            }
        }
    }
}

/// Extended GCD: returns (g, s, t) such that g = gcd(a, b) = s*a + t*b.
fn extended_gcd(a: i64, b: i64) -> (i64, i64, i64) {
    if b == 0 {
        return (a.abs(), if a >= 0 { 1 } else { -1 }, 0);
    }
    let (g, s1, t1) = extended_gcd(b, a % b);
    (g, t1, s1 - (a / b) * t1)
}

/// Greatest common divisor (always non-negative).
fn gcd(a: i64, b: i64) -> i64 {
    let (mut a, mut b) = (a.abs(), b.abs());
    while b != 0 {
        let t = b;
        b = a % b;
        a = t;
    }
    a
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::aux::loader::Loader;
    use crate::aux::Tag;
    use crate::interpreter::InterpretedFile;
    use std::sync::Arc;

    fn load_type_from_source(source: &str, type_name: &str) -> Arc<Complex> {
        let dir = std::env::temp_dir().join("alifib_test");
        std::fs::create_dir_all(&dir).expect("create temp dir");
        let path = dir.join(format!("{}_{}.ali", type_name, std::process::id()));
        std::fs::write(&path, source).expect("write temp file");
        let loader = Loader::default(vec![]);
        let file = InterpretedFile::load(&loader, path.to_str().unwrap())
            .ok().expect("fixture should load");
        let store = Arc::clone(&file.state);
        let module = store.find_module(&file.path).expect("module should exist");
        let (tag, _) = module.find_generator(type_name).expect("type not found");
        let gid = match tag { Tag::Global(gid) => *gid, _ => panic!("expected global tag") };
        let result = store.find_type(gid).expect("type entry not found").complex.clone();
        let _ = std::fs::remove_file(&path);
        result
    }

    // ── Smith Normal Form tests ──────────────────────────────────────────

    #[test]
    fn smith_identity() {
        let m = vec![vec![1, 0], vec![0, 1]];
        assert_eq!(smith_normal_form(&m), vec![1, 1]);
    }

    #[test]
    fn smith_single_entry() {
        let m = vec![vec![6]];
        assert_eq!(smith_normal_form(&m), vec![6]);
    }

    #[test]
    fn smith_with_torsion() {
        // Matrix [[2, 4], [0, 6]] should give diagonal [2, 6] after SNF.
        let m = vec![vec![2, 4], vec![0, 6]];
        let d = smith_normal_form(&m);
        assert_eq!(d, vec![2, 6]);
    }

    #[test]
    fn smith_zero_matrix() {
        let m = vec![vec![0, 0], vec![0, 0]];
        assert_eq!(smith_normal_form(&m), vec![0, 0]);
    }

    #[test]
    fn smith_unit_d3() {
        // This is the d_3 matrix from Unit in EckmannHilton.ali.
        let m = vec![
            vec![-1, 1, 1, -1],
            vec![0, 0, -1, 1],
            vec![0, 0, -1, 1],
        ];
        let d = smith_normal_form(&m);
        assert_eq!(d, vec![1, 1, 0]);
    }

    #[test]
    fn smith_rectangular() {
        // [[1, 2, 3]] → rank 1
        let m = vec![vec![1, 2, 3]];
        let d = smith_normal_form(&m);
        assert_eq!(d[0], 1);
    }

    // ── Homology tests ───────────────────────────────────────────────────

    // Idem: ob (0-cell), id : ob -> ob (1-cell), idem : id id -> id (2-cell).
    const IDEM_SRC: &str = "@Type\nIdem <<= {\n  ob,\n  id : ob -> ob,\n  idem : id id -> id\n}\n";

    // Magma: pt (0), ob : pt -> pt (1), m : ob ob -> ob (2).
    const MAGMA_SRC: &str = "@Type\nOb <<= {\n  pt,\n  ob : pt -> pt\n},\nMagma <<= {\n  attach Ob :: Ob,\n  m : Ob.ob Ob.ob -> Ob.ob\n}\n";

    // P2 models RP²: pt (0), id : pt -> pt (1), idem : id id -> id (2),
    // a : pt -> pt (1), tor : a a -> id (2).
    const P2_SRC: &str = "@Type\nP2 <<= {\n  pt,\n  id: pt -> pt,\n  idem: id id -> id,\n  a: pt -> pt,\n  tor: a a -> id\n}\n";

    // Unit from EckmannHilton: monoid with merge/split.
    const UNIT_SRC: &str = "\
@Type\n\
Equation <<= {\n\
    s0, t0,\n\
    s1: s0 -> t0, t1: s0 -> t0,\n\
    lhs: s1 -> t1, rhs: s1 -> t1,\n\
    dir: lhs -> rhs, inv: rhs -> lhs\n\
},\n\
Unit <<= {\n\
    pt,\n\
    ob: pt -> pt,\n\
    id: ob -> ob,\n\
    attach Id_id :: Equation along [\n\
        lhs => id id,\n\
        rhs => id\n\
    ],\n\
    merge: ob ob -> ob,\n\
    split: ob -> ob ob,\n\
    attach Split_merge :: Equation along [\n\
        lhs => split merge,\n\
        rhs => id\n\
    ]\n\
}\n";

    // Ob from Category: object with identity and id-id equation.
    const OB_SRC: &str = "\
@Type\n\
Eq <<= {\n\
  dom, cod,\n\
  lhs: dom -> cod, rhs: dom -> cod,\n\
  dir: lhs -> rhs, inv: rhs -> lhs\n\
},\n\
Ob <<= {\n\
  ob,\n\
  id: ob -> ob,\n\
  attach Id_id :: Eq along [\n\
    lhs => id id,\n\
    rhs => id\n\
  ]\n\
}\n";

    #[test]
    fn homology_ob_type() {
        let complex = load_type_from_source(IDEM_SRC, "Idem");
        let h = compute_homology(&complex);
        // H_0 = Z, H_1 = 0, H_2 = 0.
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1.free_rank, 1);
        assert!(h0.1.torsion.is_empty());
        let h1 = h.groups.iter().find(|(d, _)| *d == 1).unwrap();
        assert_eq!(h1.1.free_rank, 0);
        let h2 = h.groups.iter().find(|(d, _)| *d == 2).unwrap();
        assert_eq!(h2.1.free_rank, 0);
    }

    #[test]
    fn homology_magma() {
        // H_0 = Z, H_1 = 0, H_2 = 0.
        let complex = load_type_from_source(MAGMA_SRC, "Magma");
        let h = compute_homology(&complex);
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1.free_rank, 1);
        let h1 = h.groups.iter().find(|(d, _)| *d == 1).unwrap();
        assert_eq!(h1.1.free_rank, 0);
    }

    #[test]
    fn homology_p2_torsion() {
        // H_0 = Z, H_1 = Z/2, H_2 = 0.
        let complex = load_type_from_source(P2_SRC, "P2");
        let h = compute_homology(&complex);
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1, AbelianGroup { free_rank: 1, torsion: vec![] });
        let h1 = h.groups.iter().find(|(d, _)| *d == 1).unwrap();
        assert_eq!(h1.1, AbelianGroup { free_rank: 0, torsion: vec![2] });
        let h2 = h.groups.iter().find(|(d, _)| *d == 2).unwrap();
        assert_eq!(h2.1, AbelianGroup { free_rank: 0, torsion: vec![] });
    }

    #[test]
    fn homology_unit() {
        let complex = load_type_from_source(UNIT_SRC, "Unit");
        let h = compute_homology(&complex);
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1.free_rank, 1);
        let h3 = h.groups.iter().find(|(d, _)| *d == 3).unwrap();
        assert_eq!(h3.1.free_rank, 2);
    }

    #[test]
    fn homology_category() {
        let complex = load_type_from_source(OB_SRC, "Ob");
        let h = compute_homology(&complex);
        eprintln!("Ob homology:\n{}", h);
    }

    // ── Homology gallery tests ─────────────────────────────────────

    // Inline type definitions from Homology.ali (these use `attach` so
    // types that depend on Loop must be in the same source string).

    const S1_SRC: &str = "@Type\nS1 <<= { pt, a: pt -> pt }\n";
    const BOUQUET3_SRC: &str = "@Type\nBouquet3 <<= { pt, a: pt -> pt, b: pt -> pt, c: pt -> pt }\n";
    const TORUS_SRC: &str = "@Type\nTorus <<= { pt, a: pt -> pt, b: pt -> pt, f: a b -> b a }\n";
    const SIGMA2_SRC: &str = "@Type\nSigma2 <<= {\n  pt,\n  a: pt -> pt, b: pt -> pt, c: pt -> pt, d: pt -> pt,\n  f: a b c d -> b a d c\n}\n";
    const KLEIN_SRC: &str = "@Type\nKlein <<= { pt, a: pt -> pt, b: pt -> pt, f: a -> a b b }\n";
    const DUNCE_SRC: &str = "@Type\nDunce <<= { pt, a: pt -> pt, f: a -> a a }\n";

    const S2_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nS2 <<= { attach L :: Loop, s: L.id -> L.id }\n";
    const RP2_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nRP2 <<= { attach L :: Loop, a: L.pt -> L.pt, face: L.id -> a a }\n";
    const N3_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nN3 <<= {\n  attach L :: Loop,\n  a: L.pt -> L.pt, b: L.pt -> L.pt, c: L.pt -> L.pt,\n  face: L.id -> a a b b c c\n}\n";
    const LENS5_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nLens5 <<= { attach L :: Loop, a: L.pt -> L.pt, face: L.id -> a a a a a }\n";
    const KLEIN4_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nKlein4 <<= {\n  attach L1 :: Loop,\n  attach L2 :: Loop along [ pt => L1.pt ],\n  a: L1.pt -> L1.pt, b: L1.pt -> L1.pt,\n  f1: L1.id -> a a, f2: L2.id -> b b\n}\n";
    const WEDGE_S2_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nWedge_S2 <<= { attach L :: Loop, s1: L.id -> L.id, s2: L.id -> L.id }\n";
    const S3_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nS3 <<= { attach L :: Loop, id2: L.id -> L.id, idem2: id2 id2 -> id2, s: id2 -> id2 }\n";
    const T3_SRC: &str = "@Type\nT3 <<= {\n  pt,\n  a: pt -> pt, b: pt -> pt, c: pt -> pt,\n  f_ab: a b -> b a, f_ac: a c -> c a, f_bc: b c -> c b,\n  vol: (f_ab c) #1 (b f_ac) #1 (f_bc a)\n    -> (a f_bc) #1 (f_ac b) #1 (c f_ab)\n}\n";
    const RP3_SRC: &str = "@Type\nLoop <<= { pt, id: pt -> pt, idem: id id -> id },\nRP3 <<= {\n  attach L :: Loop,\n  a: L.pt -> L.pt, face: L.id -> a a,\n  id2: L.id -> L.id, idem2: id2 id2 -> id2, s: id2 -> id2\n}\n";

    fn assert_homology(source: &str, type_name: &str, expected: &[(usize, usize, &[i64])], chi: i64) {
        let complex = load_type_from_source(source, type_name);
        let h = compute_homology(&complex);
        for &(dim, free_rank, torsion) in expected {
            let group = h.groups.iter().find(|(d, _)| *d == dim)
                .unwrap_or_else(|| panic!("H_{} missing for {}", dim, type_name));
            assert_eq!(group.1.free_rank, free_rank,
                "H_{} free rank for {}: expected {}, got {}", dim, type_name, free_rank, group.1.free_rank);
            assert_eq!(group.1.torsion, torsion,
                "H_{} torsion for {}: expected {:?}, got {:?}", dim, type_name, torsion, group.1.torsion);
        }
        assert_eq!(h.euler_characteristic, chi,
            "Euler characteristic for {}: expected {}, got {}", type_name, chi, h.euler_characteristic);
    }

    #[test]
    fn homology_s1() {
        assert_homology(S1_SRC, "S1", &[(0, 1, &[]), (1, 1, &[])], 0);
    }

    #[test]
    fn homology_bouquet3() {
        assert_homology(BOUQUET3_SRC, "Bouquet3", &[(0, 1, &[]), (1, 3, &[])], -2);
    }

    #[test]
    fn homology_s2() {
        assert_homology(S2_SRC, "S2", &[(0, 1, &[]), (1, 0, &[]), (2, 1, &[])], 2);
    }

    #[test]
    fn homology_torus() {
        assert_homology(TORUS_SRC, "Torus", &[(0, 1, &[]), (1, 2, &[]), (2, 1, &[])], 0);
    }

    #[test]
    fn homology_sigma2() {
        assert_homology(SIGMA2_SRC, "Sigma2", &[(0, 1, &[]), (1, 4, &[]), (2, 1, &[])], -2);
    }

    #[test]
    fn homology_rp2() {
        assert_homology(RP2_SRC, "RP2", &[(0, 1, &[]), (1, 0, &[2]), (2, 0, &[])], 1);
    }

    #[test]
    fn homology_klein() {
        assert_homology(KLEIN_SRC, "Klein", &[(0, 1, &[]), (1, 1, &[2]), (2, 0, &[])], 0);
    }

    #[test]
    fn homology_n3() {
        assert_homology(N3_SRC, "N3", &[(0, 1, &[]), (1, 2, &[2]), (2, 0, &[])], -1);
    }

    #[test]
    fn homology_lens5() {
        assert_homology(LENS5_SRC, "Lens5", &[(0, 1, &[]), (1, 0, &[5]), (2, 0, &[])], 1);
    }

    #[test]
    fn homology_klein4() {
        assert_homology(KLEIN4_SRC, "Klein4", &[(0, 1, &[]), (1, 0, &[2, 2]), (2, 0, &[])], 1);
    }

    #[test]
    fn homology_dunce() {
        assert_homology(DUNCE_SRC, "Dunce", &[(0, 1, &[]), (1, 0, &[]), (2, 0, &[])], 1);
    }

    #[test]
    fn homology_wedge_s2() {
        assert_homology(WEDGE_S2_SRC, "Wedge_S2", &[(0, 1, &[]), (1, 0, &[]), (2, 2, &[])], 3);
    }

    #[test]
    fn homology_s3() {
        assert_homology(S3_SRC, "S3", &[(0, 1, &[]), (1, 0, &[]), (2, 0, &[]), (3, 1, &[])], 0);
    }

    #[test]
    fn homology_t3() {
        assert_homology(T3_SRC, "T3", &[(0, 1, &[]), (1, 3, &[]), (2, 3, &[]), (3, 1, &[])], 0);
    }

    #[test]
    fn homology_rp3() {
        assert_homology(RP3_SRC, "RP3", &[(0, 1, &[]), (1, 0, &[2]), (2, 0, &[]), (3, 1, &[])], 0);
    }

    // ── Torsion-witness tests ────────────────────────────────────────────

    fn assert_witness_consistent(source: &str, type_name: &str, expected_dim: usize, expected_witnesses: &[(i64, &[(&str, i64)])]) {
        let complex = load_type_from_source(source, type_name);
        let h = compute_homology(&complex);
        let witnesses = h.torsion_witnesses.get(&expected_dim)
            .unwrap_or_else(|| panic!("no torsion witnesses at dim {} for {}", expected_dim, type_name));
        assert_eq!(witnesses.len(), expected_witnesses.len(),
            "{} dim {}: expected {} witnesses, got {}",
            type_name, expected_dim, expected_witnesses.len(), witnesses.len());
        for (w, (exp_order, exp_cycle)) in witnesses.iter().zip(expected_witnesses.iter()) {
            assert_eq!(w.order, *exp_order,
                "{} dim {}: witness order mismatch", type_name, expected_dim);
            let got: Vec<(String, i64)> = w.cycle.clone();
            let exp: Vec<(String, i64)> = exp_cycle.iter().map(|(s, c)| (s.to_string(), *c)).collect();
            assert_eq!(got, exp,
                "{} dim {}: cycle mismatch — got {:?}, expected {:?}",
                type_name, expected_dim, got, exp);
        }
    }

    const TORSION_SRC: &str = "@Type\nTorsion <<= { pt, a : pt -> pt, double : a a -> a a a a }\n";
    const K_CONTENTION_SRC: &str = "@Type\nKContention <<= { pt, a : pt -> pt, race : a a a a a -> a a a a a a a a a a }\n";
    const ABA_UNSAFE_SRC: &str = "@Type\nABAUnsafe <<= { pt, push : pt -> pt, pop : pt -> pt, aba : push pop push pop push pop -> push pop }\n";
    const LINEARIZABLE_CAS_SRC: &str = "@Type\nLinearizableCAS <<= { pt, push : pt -> pt, linearize : push push -> push push }\n";

    #[test]
    fn witness_torsion_example() {
        // a^2 → a^4: H_1 = Z/2 generated by [a].
        assert_witness_consistent(TORSION_SRC, "Torsion", 1, &[(2, &[("a", 1)])]);
    }

    #[test]
    fn witness_races_k_contention() {
        // a^5 → a^10: H_1 = Z/5 generated by [a].
        assert_witness_consistent(K_CONTENTION_SRC, "KContention", 1, &[(5, &[("a", 1)])]);
    }

    #[test]
    fn witness_aba_bug() {
        // (push pop)^3 → (push pop): H_1 = Z + Z/2.
        assert_witness_consistent(ABA_UNSAFE_SRC, "ABAUnsafe", 1, &[(2, &[("pop", 1), ("push", 1)])]);
    }

    #[test]
    fn witness_none_when_torsion_free() {
        let complex = load_type_from_source(LINEARIZABLE_CAS_SRC, "LinearizableCAS");
        let h = compute_homology(&complex);
        assert!(h.torsion_witnesses.is_empty(),
            "expected no torsion witnesses for torsion-free type, got {:?}", h.torsion_witnesses);
    }

    #[test]
    fn witness_rp2() {
        let complex = load_type_from_source(RP2_SRC, "RP2");
        let h = compute_homology(&complex);
        let ws = h.torsion_witnesses.get(&1).expect("RP2 should have torsion at H_1");
        assert_eq!(ws.len(), 1);
        assert_eq!(ws[0].order, 2);
        assert!(!ws[0].cycle.is_empty(), "witness cycle should be nonempty");
    }

    // ── Tracked SNF normalisation ────────────────────────────────────────

    /// Apply `enforce_divisibility_tracked` to a hand-built non-divisibility-ordered
    /// `(diag, u_inv)` pair and check the resulting diag and u_inv satisfy the
    /// change-of-basis invariant: column `i` of u_inv is a chain whose `diag[i]`-
    /// multiple lies in the image of the assumed SNF matrix (here `diag(3, 2)`).
    #[test]
    fn tracked_enforce_divisibility_crt() {
        let mut diag = vec![3, 2];
        let mut u_inv = vec![vec![1, 0], vec![0, 1]];
        let mut v = vec![vec![1, 0], vec![0, 1]];
        enforce_divisibility_tracked(&mut diag, &mut u_inv, &mut v);
        assert_eq!(diag, vec![1, 6]);

        // After enforce, for M = diag(3, 2):
        //   column 0 of u_inv times diag[0]=1 should lie in im(M) = 3Z × 2Z;
        //   column 1 of u_inv times diag[1]=6 should lie in im(M), but 1·col1 should not.
        let m = [[3, 0], [0, 2]];
        for col in 0..2 {
            let z = [u_inv[0][col], u_inv[1][col]];
            let d = diag[col];
            let scaled = [d * z[0], d * z[1]];
            assert_eq!(scaled[0] % m[0][0], 0,
                "col {} of u_inv: {}·col not in im(M) (row 0)", col, d);
            assert_eq!(scaled[1] % m[1][1], 0,
                "col {} of u_inv: {}·col not in im(M) (row 1)", col, d);
            if d > 1 {
                assert!(
                    z[0] % m[0][0] != 0 || z[1] % m[1][1] != 0,
                    "col {} claims order {} but z itself is already a boundary", col, d
                );
            }
        }

        // Additionally: d(v column i) should equal diag[i] · u_inv column i.
        // Here d = M = diag(3, 2) (matrix multiplication).
        for col in 0..2 {
            let p = [v[0][col], v[1][col]];
            let d = diag[col];
            let z = [u_inv[0][col], u_inv[1][col]];
            let mp = [m[0][0] * p[0] + m[0][1] * p[1], m[1][0] * p[0] + m[1][1] * p[1]];
            let dz = [d * z[0], d * z[1]];
            assert_eq!(mp, dz,
                "col {}: M·p = {:?}, d·z = {:?}", col, mp, dz);
        }
    }

    /// Apply `sort_diag_tracked` on a hand-built `(diag, u_inv, v)` and check
    /// both the diag ordering and that the paired column permutation is
    /// applied to both change-of-basis matrices.
    #[test]
    fn tracked_sort_diag_permutes_witnesses() {
        let mut diag = vec![0, 3, 0, 2];
        let mut u_inv = vec![
            vec![10, 11, 12, 13],
            vec![20, 21, 22, 23],
            vec![30, 31, 32, 33],
            vec![40, 41, 42, 43],
        ];
        let mut v = vec![
            vec![100, 101, 102, 103],
            vec![200, 201, 202, 203],
            vec![300, 301, 302, 303],
            vec![400, 401, 402, 403],
        ];
        sort_diag_tracked(&mut diag, &mut u_inv, &mut v);
        assert_eq!(diag, vec![2, 3, 0, 0]);
        // u_inv: col 3 (value 2) → col 0; col 1 (value 3) → col 1.
        assert_eq!(u_inv[0][0], 13);
        assert_eq!(u_inv[0][1], 11);
        assert_eq!(u_inv[1][0], 23);
        assert_eq!(u_inv[1][1], 21);
        // v: same permutation.
        assert_eq!(v[0][0], 103);
        assert_eq!(v[0][1], 101);
        assert_eq!(v[1][0], 203);
        assert_eq!(v[1][1], 201);
    }

    fn verify_witnesses_valid(complex: &Complex, type_name: &str) {
        use std::collections::HashMap as Map;

        let h = compute_homology(complex);

        let mut gens_by_dim: Map<usize, Vec<String>> = Map::new();
        for (name, _, dim) in complex.generators_iter() {
            gens_by_dim.entry(dim).or_default().push(name.clone());
        }
        for v in gens_by_dim.values_mut() { v.sort(); }

        for (&n, witnesses) in &h.torsion_witnesses {
            let row_gens_n = match gens_by_dim.get(&n) { Some(v) => v, None => continue };
            let row_gens_n1 = gens_by_dim.get(&(n.saturating_sub(1)));

            for w in witnesses {
                let mut z = vec![0i64; row_gens_n.len()];
                for (name, coeff) in &w.cycle {
                    let idx = row_gens_n.iter().position(|g| g == name)
                        .unwrap_or_else(|| panic!("witness names unknown generator {}", name));
                    z[idx] = *coeff;
                }

                if let Some(row_gens_below) = row_gens_n1 {
                    let dn_z = apply_dn_to_chain(complex, &z, n, row_gens_n, row_gens_below);
                    assert!(dn_z.iter().all(|&c| c == 0),
                        "{} dim {}: witness {} not a cycle; d_n(z) = {:?}",
                        type_name, n, w, dn_z);
                }

                assert!(z.iter().any(|&c| c != 0),
                    "{} dim {}: witness is the zero chain", type_name, n);

                if let Some(row_gens_above) = gens_by_dim.get(&(n + 1)) {
                    let mut p = vec![0i64; row_gens_above.len()];
                    for (name, coeff) in &w.preimage {
                        let idx = row_gens_above.iter().position(|g| g == name)
                            .unwrap_or_else(|| panic!(
                                "preimage names unknown (n+1)-generator {}", name));
                        p[idx] = *coeff;
                    }
                    let dn1_p = apply_dn_to_chain(complex, &p, n + 1, row_gens_above, row_gens_n);
                    let order_z: Vec<i64> = z.iter().map(|c| c * w.order).collect();
                    assert_eq!(dn1_p, order_z,
                        "{} dim {}: d_{}(preimage) != {}·cycle\n  preimage = {:?}\n  cycle = {:?}\n  d·preimage = {:?}\n  order·cycle = {:?}",
                        type_name, n, n + 1, w.order, w.preimage, w.cycle, dn1_p, order_z);
                }
            }
        }
    }

    fn apply_dn_to_chain(
        complex: &Complex,
        z: &[i64],
        _n: usize,
        row_gens_n: &[String],
        row_gens_below: &[String],
    ) -> Vec<i64> {
        use std::collections::HashMap as Map;
        let row_index: Map<&str, usize> = row_gens_below.iter().enumerate()
            .map(|(i, s)| (s.as_str(), i)).collect();
        let mut result = vec![0i64; row_gens_below.len()];
        for (col, coeff) in z.iter().enumerate() {
            if *coeff == 0 { continue; }
            let name = &row_gens_n[col];
            let Some(classifier) = complex.classifier(name) else { continue };
            let d = classifier.top_dim();
            if d < 1 { continue; }
            let labels_below = classifier.labels_at(d - 1);
            for &face_pos in &classifier.shape.faces_of(super::super::ogposet::Sign::Output, d, 0) {
                if let Some(tag) = labels_below.and_then(|ls| ls.get(face_pos)) {
                    if let Some(name) = complex.find_generator_by_tag(tag) {
                        if let Some(&row) = row_index.get(name.as_str()) {
                            result[row] += *coeff;
                        }
                    }
                }
            }
            for &face_pos in &classifier.shape.faces_of(super::super::ogposet::Sign::Input, d, 0) {
                if let Some(tag) = labels_below.and_then(|ls| ls.get(face_pos)) {
                    if let Some(name) = complex.find_generator_by_tag(tag) {
                        if let Some(&row) = row_index.get(name.as_str()) {
                            result[row] -= *coeff;
                        }
                    }
                }
            }
        }
        result
    }

    const LOST_UPDATE_SRC: &str = "@Type\nLostUpdate <<= { pt, a : pt -> pt, race : a a -> a a a a }\n";
    const TRIPLE_CONTENTION_SRC: &str = "@Type\nTripleContention <<= { pt, a : pt -> pt, race : a a a -> a a a a a a }\n";
    const TORN_OP_BUG_SRC: &str = "@Type\nTornOpBug <<= { pt, push : pt -> pt, torn : push push -> push push push push }\n";

    #[test]
    fn all_witnesses_are_cycles() {
        for (src, name) in [
            (TORSION_SRC, "Torsion"),
            (LOST_UPDATE_SRC, "LostUpdate"),
            (TRIPLE_CONTENTION_SRC, "TripleContention"),
            (K_CONTENTION_SRC, "KContention"),
            (TORN_OP_BUG_SRC, "TornOpBug"),
            (ABA_UNSAFE_SRC, "ABAUnsafe"),
            (RP2_SRC, "RP2"),
            (KLEIN_SRC, "Klein"),
            (LENS5_SRC, "Lens5"),
            (KLEIN4_SRC, "Klein4"),
            (N3_SRC, "N3"),
        ] {
            let complex = load_type_from_source(src, name);
            verify_witnesses_valid(&complex, name);
        }
    }
}
