//! Cellular homology of a [`Complex`].
//!
//! Computes the chain complex of free abelian groups generated by the generators
//! of each dimension, with differentials defined by boundary face multiplicities,
//! then computes homology via Smith Normal Form.

use std::collections::HashMap;
use super::complex::Complex;

/// A finitely generated abelian group, represented as a free rank plus torsion invariants.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AbelianGroup {
    /// Rank of the free part (number of Z summands).
    pub free_rank: usize,
    /// Torsion invariants [d_1, d_2, ...] with 1 < d_1 | d_2 | ... | d_k.
    pub torsion: Vec<i64>,
}

impl std::fmt::Display for AbelianGroup {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut parts = Vec::new();
        if self.free_rank > 0 {
            if self.free_rank == 1 {
                parts.push("Z".to_string());
            } else {
                parts.push(format!("Z^{}", self.free_rank));
            }
        }
        for &d in &self.torsion {
            parts.push(format!("Z/{}", d));
        }
        if parts.is_empty() {
            write!(f, "0")
        } else {
            write!(f, "{}", parts.join(" + "))
        }
    }
}

/// The cellular homology of a complex, indexed by dimension.
#[derive(Debug)]
pub struct Homology {
    /// H_n for each dimension n that has generators.
    pub groups: Vec<(usize, AbelianGroup)>,
    /// Euler characteristic: Σ (-1)^n |C_n|.
    pub euler_characteristic: i64,
}

impl Homology {
    /// Euler characteristic computed from the homology groups (should equal
    /// the one computed from the chain complex ranks).
    pub fn euler_from_homology(&self) -> i64 {
        self.groups.iter().map(|(n, g)| {
            let rank = g.free_rank as i64;
            if n % 2 == 0 { rank } else { -rank }
        }).sum()
    }
}

impl std::fmt::Display for Homology {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (dim, group) in &self.groups {
            writeln!(f, "H_{} = {}", dim, group)?;
        }
        writeln!(f, "χ = {}", self.euler_characteristic)?;
        Ok(())
    }
}

/// Compute the cellular homology of a complex.
///
/// The chain complex C_n is free on the n-dimensional generators.
/// The differential d_n: C_n → C_{n-1} sends generator g to
/// (sum of output (n-1)-faces) - (sum of input (n-1)-faces),
/// counted with multiplicity.
pub fn compute_homology(complex: &Complex) -> Homology {
    // Collect generators by dimension, with stable ordering.
    let mut gens_by_dim: HashMap<usize, Vec<String>> = HashMap::new();
    for (name, _, dim) in complex.generators_iter() {
        gens_by_dim.entry(dim).or_default().push(name.clone());
    }
    // Sort within each dimension for deterministic ordering.
    for v in gens_by_dim.values_mut() {
        v.sort();
    }

    if gens_by_dim.is_empty() {
        return Homology { groups: vec![], euler_characteristic: 0 };
    }


    let max_dim = *gens_by_dim.keys().max().unwrap();

    // Build differential matrices.
    // diff[n] is the matrix for d_n: C_n → C_{n-1}.
    // Rows indexed by (n-1)-generators, columns by n-generators.
    let mut differentials: HashMap<usize, Vec<Vec<i64>>> = HashMap::new();

    for n in 1..=max_dim {
        let Some(cols) = gens_by_dim.get(&n) else { continue; };
        let Some(rows) = gens_by_dim.get(&(n - 1)) else { continue; };
        if cols.is_empty() || rows.is_empty() { continue; }

        // Map (n-1)-generator names to row indices.
        let row_index: HashMap<&str, usize> = rows.iter()
            .enumerate()
            .map(|(i, name)| (name.as_str(), i))
            .collect();

        let num_rows = rows.len();
        let num_cols = cols.len();

        let mut matrix = vec![vec![0i64; num_cols]; num_rows];

        for (col, gen_name) in cols.iter().enumerate() {
            let Some(classifier) = complex.classifier(gen_name) else { continue; };
            let d = classifier.top_dim();
            if d < 1 { continue; }

            // The classifier has a single top-dimensional cell at position 0.
            // Read its output and input faces directly from the ogposet.
            let labels_below = classifier.labels_at(d - 1);

            // Output faces: +1 for each occurrence.
            for &face_pos in &classifier.shape.faces_of(
                super::ogposet::Sign::Output, d, 0,
            ) {
                if let Some(tag) = labels_below.and_then(|ls| ls.get(face_pos)) {
                    if let Some(name) = complex.find_generator_by_tag(tag) {
                        if let Some(&row) = row_index.get(name.as_str()) {
                            matrix[row][col] += 1;
                        }
                    }
                }
            }

            // Input faces: -1 for each occurrence.
            for &face_pos in &classifier.shape.faces_of(
                super::ogposet::Sign::Input, d, 0,
            ) {
                if let Some(tag) = labels_below.and_then(|ls| ls.get(face_pos)) {
                    if let Some(name) = complex.find_generator_by_tag(tag) {
                        if let Some(&row) = row_index.get(name.as_str()) {
                            matrix[row][col] -= 1;
                        }
                    }
                }
            }
        }

        differentials.insert(n, matrix);
    }

    // Sanity check: d_n ∘ d_{n+1} = 0 for all n.
    for n in 2..=max_dim {
        if let (Some(dn), Some(dn1)) = (differentials.get(&n), differentials.get(&(n - 1))) {
            // dn1 is (n-2)×(n-1), dn is (n-1)×n. Product dn1 * dn should be zero.
            // Actually: d_{n-1} ∘ d_n, i.e. multiply d_{n-1} (rows=n-2 gens, cols=n-1 gens)
            // by d_n (rows=n-1 gens, cols=n gens).
            // But differentials[n] has rows indexed by (n-1)-gens, cols by n-gens.
            // differentials[n-1] has rows indexed by (n-2)-gens, cols by (n-1)-gens.
            // Product: differentials[n-1] * differentials[n] should be zero.
            let product = mat_mul(dn1, dn);
            debug_assert!(
                product.iter().all(|row| row.iter().all(|&v| v == 0)),
                "d² ≠ 0 at dimension {}: d_{} ∘ d_{} is nonzero",
                n, n - 1, n,
            );
        }
    }

    // Compute homology at each dimension.
    let mut groups = Vec::new();
    let mut dims: Vec<usize> = gens_by_dim.keys().copied().collect();
    dims.sort();

    for &n in &dims {
        let num_gens = gens_by_dim[&n].len();

        // d_n: C_n → C_{n-1}  (may not exist if n=0 or no (n-1)-generators)
        let rank_dn = differentials.get(&n)
            .map(|m| matrix_rank(m))
            .unwrap_or(0);

        // d_{n+1}: C_{n+1} → C_n  (may not exist)
        let smith_dn1 = differentials.get(&(n + 1))
            .map(|m| {
                smith_normal_form(m)
            });

        let (rank_dn1, torsion) = match smith_dn1 {
            Some(diag) => {
                let rank = diag.iter().filter(|&&d| d != 0).count();
                let torsion: Vec<i64> = diag.iter()
                    .filter(|&&d| d > 1)
                    .copied()
                    .collect();
                (rank, torsion)
            }
            None => (0, vec![]),
        };

        let free_rank = num_gens - rank_dn - rank_dn1;
        groups.push((n, AbelianGroup { free_rank, torsion }));
    }

    // Euler characteristic: Σ (-1)^n |C_n|.
    let euler_characteristic: i64 = gens_by_dim.iter().map(|(&n, v)| {
        let count = v.len() as i64;
        if n % 2 == 0 { count } else { -count }
    }).sum();

    let result = Homology { groups, euler_characteristic };
    debug_assert_eq!(
        result.euler_characteristic, result.euler_from_homology(),
        "Euler characteristic mismatch: chain complex gives {}, homology gives {}",
        result.euler_characteristic, result.euler_from_homology(),
    );
    result
}

/// Multiply two integer matrices.
fn mat_mul(a: &[Vec<i64>], b: &[Vec<i64>]) -> Vec<Vec<i64>> {
    let rows_a = a.len();
    let cols_b = if b.is_empty() { 0 } else { b[0].len() };
    let inner = if a.is_empty() { 0 } else { a[0].len() };
    let mut c = vec![vec![0i64; cols_b]; rows_a];
    for i in 0..rows_a {
        for k in 0..inner {
            if a[i][k] == 0 { continue; }
            for j in 0..cols_b {
                c[i][j] += a[i][k] * b[k][j];
            }
        }
    }
    c
}

// ── Smith Normal Form ────────────────────────────────────────────────────────

/// Compute the Smith Normal Form diagonal of an integer matrix.
///
/// Returns the diagonal entries [d_1, d_2, ...] with d_i | d_{i+1},
/// sorted so that zero entries come last.
fn smith_normal_form(matrix: &[Vec<i64>]) -> Vec<i64> {
    if matrix.is_empty() { return vec![]; }
    let num_rows = matrix.len();
    let num_cols = matrix[0].len();
    if num_cols == 0 { return vec![]; }

    // Work on a mutable copy.
    let mut m: Vec<Vec<i64>> = matrix.to_vec();

    let min_dim = num_rows.min(num_cols);
    let mut pivot = 0;

    while pivot < min_dim {
        // Find a nonzero entry in the submatrix m[pivot..][pivot..].
        if !find_and_move_pivot(&mut m, pivot, num_rows, num_cols) {
            break; // remaining submatrix is zero
        }

        // Eliminate entries in the pivot row and column.
        // After eliminating, check if the pivot divides all entries in the
        // remaining submatrix. If not, add a non-divisible entry's row to
        // the pivot row and repeat. The pivot value strictly decreases each
        // time a GCD reduction occurs, guaranteeing termination.
        loop {
            // Phase 1: zero out pivot column and row.
            loop {
                eliminate_column(&mut m, pivot, num_rows);
                eliminate_row(&mut m, pivot, num_cols);
                if is_pivot_clean(&m, pivot, num_rows, num_cols) { break; }
            }
            // Phase 2: check divisibility in the remaining submatrix.
            let pv = m[pivot][pivot];
            if pv == 0 { break; }
            let mut found_bad = false;
            'search: for r in (pivot + 1)..num_rows {
                for c in (pivot + 1)..num_cols {
                    if m[r][c] % pv != 0 {
                        // Add row r to pivot row to introduce a non-divisible entry,
                        // which will reduce the pivot via GCD on the next iteration.
                        for j in 0..num_cols {
                            m[pivot][j] += m[r][j];
                        }
                        found_bad = true;
                        break 'search;
                    }
                }
            }
            if !found_bad { break; }
        }

        // Ensure the pivot is positive.
        if m[pivot][pivot] < 0 {
            for j in 0..num_cols { m[pivot][j] = -m[pivot][j]; }
        }

        pivot += 1;
    }

    // Extract diagonal and enforce divisibility.
    let mut diag: Vec<i64> = (0..min_dim).map(|i| m[i][i].abs()).collect();
    enforce_divisibility(&mut diag);

    // Sort: nonzero first (in divisibility order), then zeros.
    diag.sort_by(|a, b| {
        match (a == &0, b == &0) {
            (true, false) => std::cmp::Ordering::Greater,
            (false, true) => std::cmp::Ordering::Less,
            _ => a.cmp(b),
        }
    });

    diag
}

/// Compute the rank of an integer matrix (number of nonzero rows in its row echelon form).
fn matrix_rank(matrix: &[Vec<i64>]) -> usize {
    // Use Smith form — rank = number of nonzero diagonal entries.
    smith_normal_form(matrix).iter().filter(|&&d| d != 0).count()
}

/// Find a nonzero entry in m[pivot..][pivot..] and swap it to (pivot, pivot).
fn find_and_move_pivot(m: &mut [Vec<i64>], pivot: usize, nrows: usize, ncols: usize) -> bool {
    // Prefer the smallest nonzero absolute value for better elimination.
    let mut best: Option<(usize, usize, i64)> = None;
    for r in pivot..nrows {
        for c in pivot..ncols {
            let v = m[r][c].abs();
            if v > 0 {
                if best.is_none() || v < best.unwrap().2 {
                    best = Some((r, c, v));
                }
            }
        }
    }
    let Some((br, bc, _)) = best else { return false; };
    m.swap(pivot, br);
    for row in m.iter_mut() {
        row.swap(pivot, bc);
    }
    true
}

/// Eliminate entries in the pivot column below the pivot using row operations.
///
/// Uses simple subtraction when the pivot divides the entry (avoids changing
/// the pivot row). Falls back to GCD-based operations when it doesn't.
fn eliminate_column(m: &mut [Vec<i64>], pivot: usize, nrows: usize) {
    let ncols = m[0].len();
    let pv = m[pivot][pivot];
    for r in (pivot + 1)..nrows {
        if m[r][pivot] == 0 { continue; }
        if pv != 0 && m[r][pivot] % pv == 0 {
            // Simple case: subtract a multiple of the pivot row.
            let q = m[r][pivot] / pv;
            for j in 0..ncols {
                m[r][j] -= q * m[pivot][j];
            }
        } else {
            // GCD case: replace pivot with gcd.
            let (g, s, t) = extended_gcd(pv, m[r][pivot]);
            let a = pv / g;
            let b = m[r][pivot] / g;
            let old_pivot_row = m[pivot].clone();
            let old_r_row = m[r].clone();
            for j in 0..ncols {
                m[pivot][j] = s * old_pivot_row[j] + t * old_r_row[j];
                m[r][j] = -b * old_pivot_row[j] + a * old_r_row[j];
            }
        }
    }
}

/// Eliminate entries in the pivot row to the right of the pivot using column operations.
///
/// Uses simple subtraction when the pivot divides the entry. Falls back to
/// GCD-based operations when it doesn't.
fn eliminate_row(m: &mut [Vec<i64>], pivot: usize, ncols: usize) {
    let nrows = m.len();
    let pv = m[pivot][pivot];
    for c in (pivot + 1)..ncols {
        if m[pivot][c] == 0 { continue; }
        if pv != 0 && m[pivot][c] % pv == 0 {
            let q = m[pivot][c] / pv;
            for r in 0..nrows {
                m[r][c] -= q * m[r][pivot];
            }
        } else {
            let (g, s, t) = extended_gcd(pv, m[pivot][c]);
            let a = pv / g;
            let b = m[pivot][c] / g;
            let old_pivot_col: Vec<i64> = (0..nrows).map(|r| m[r][pivot]).collect();
            let old_c_col: Vec<i64> = (0..nrows).map(|r| m[r][c]).collect();
            for r in 0..nrows {
                m[r][pivot] = s * old_pivot_col[r] + t * old_c_col[r];
                m[r][c] = -b * old_pivot_col[r] + a * old_c_col[r];
            }
        }
    }
}

/// Check if all entries in the pivot's row and column (outside the pivot) are zero.
fn is_pivot_clean(m: &[Vec<i64>], pivot: usize, nrows: usize, ncols: usize) -> bool {
    for r in (pivot + 1)..nrows {
        if m[r][pivot] != 0 { return false; }
    }
    for c in (pivot + 1)..ncols {
        if m[pivot][c] != 0 { return false; }
    }
    true
}

/// Enforce the divisibility condition d_i | d_{i+1} on the diagonal.
fn enforce_divisibility(diag: &mut Vec<i64>) {
    let n = diag.len();
    let mut changed = true;
    while changed {
        changed = false;
        for i in 0..n.saturating_sub(1) {
            if diag[i] == 0 || diag[i + 1] == 0 { continue; }
            if diag[i + 1] % diag[i] != 0 {
                let g = gcd(diag[i], diag[i + 1]);
                let l = diag[i] / g * diag[i + 1]; // lcm
                diag[i] = g;
                diag[i + 1] = l;
                changed = true;
            }
        }
    }
}

/// Extended GCD: returns (g, s, t) such that g = gcd(a, b) = s*a + t*b.
fn extended_gcd(a: i64, b: i64) -> (i64, i64, i64) {
    if b == 0 {
        return (a.abs(), if a >= 0 { 1 } else { -1 }, 0);
    }
    let (g, s1, t1) = extended_gcd(b, a % b);
    (g, t1, s1 - (a / b) * t1)
}

/// Greatest common divisor (always non-negative).
fn gcd(a: i64, b: i64) -> i64 {
    let (mut a, mut b) = (a.abs(), b.abs());
    while b != 0 {
        let t = b;
        b = a % b;
        a = t;
    }
    a
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::aux::loader::Loader;
    use crate::aux::Tag;
    use crate::interpreter::InterpretedFile;
    use std::path::PathBuf;
    use std::sync::Arc;

    fn fixture(name: &str) -> String {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name)
            .to_string_lossy()
            .into_owned()
    }

    fn example(name: &str) -> String {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("examples")
            .join(name)
            .to_string_lossy()
            .into_owned()
    }

    fn load_type(path: &str, type_name: &str) -> Arc<Complex> {
        let loader = Loader::default(vec![]);
        let file = InterpretedFile::load(&loader, path).ok().expect("fixture should load");
        let store = Arc::clone(&file.state);
        let module = store.find_module(&file.path).expect("module should exist");
        let (tag, _) = module.find_generator(type_name).expect("type not found");
        let gid = match tag { Tag::Global(gid) => *gid, _ => panic!("expected global tag") };
        store.find_type(gid).expect("type entry not found").complex.clone()
    }

    // ── Smith Normal Form tests ──────────────────────────────────────────

    #[test]
    fn smith_identity() {
        let m = vec![vec![1, 0], vec![0, 1]];
        assert_eq!(smith_normal_form(&m), vec![1, 1]);
    }

    #[test]
    fn smith_single_entry() {
        let m = vec![vec![6]];
        assert_eq!(smith_normal_form(&m), vec![6]);
    }

    #[test]
    fn smith_with_torsion() {
        // Matrix [[2, 4], [0, 6]] should give diagonal [2, 6] after SNF.
        let m = vec![vec![2, 4], vec![0, 6]];
        let d = smith_normal_form(&m);
        assert_eq!(d, vec![2, 6]);
    }

    #[test]
    fn smith_zero_matrix() {
        let m = vec![vec![0, 0], vec![0, 0]];
        assert_eq!(smith_normal_form(&m), vec![0, 0]);
    }

    #[test]
    fn smith_unit_d3() {
        // This is the d_3 matrix from Unit in EckmannHilton.ali.
        let m = vec![
            vec![-1, 1, 1, -1],
            vec![0, 0, -1, 1],
            vec![0, 0, -1, 1],
        ];
        let d = smith_normal_form(&m);
        assert_eq!(d, vec![1, 1, 0]);
    }

    #[test]
    fn smith_rectangular() {
        // [[1, 2, 3]] → rank 1
        let m = vec![vec![1, 2, 3]];
        let d = smith_normal_form(&m);
        assert_eq!(d[0], 1);
    }

    // ── Homology tests ───────────────────────────────────────────────────

    #[test]
    fn homology_ob_type() {
        // Ob has: pt (dim 0), ob (dim 1).
        // d_1(ob) = pt - pt = 0.
        // H_0 = Z (one 0-gen, rank(d_1) = 0, rank(d_1) used from below = 0).
        // H_1 = Z (one 1-gen, ker(d_1) = 1, im(d_2) = 0).
        let complex = load_type(&fixture("Idem.ali"), "Idem");
        let h = compute_homology(&complex);
        eprintln!("{}", h);
        // Idem has: ob (dim 0), id (dim 1), idem (dim 2).
        // d_1(id) = ob - ob = 0 → rank(d_1) = 0
        // d_2(idem) = id - 2*id = -id → rank(d_2) = 1
        // H_0 = Z^1 (1 gen, rank d_1 = 0, rank d_1 from below = 0)
        // H_1 = Z^0 (1 gen, rank d_1 = 0, rank d_2 = 1 → 1 - 0 - 1 = 0)
        // H_2 = Z^1 (1 gen, rank d_2 = 1, no d_3 → 1 - 1 - 0 = 0)
        // Wait, let me recalculate...
        // Actually: idem : id id -> id. So output face has 1 copy of id, input face has 2 copies.
        // d_2(idem) = 1*id - 2*id = -id. Matrix is [-1]. Rank = 1.
        // H_0: 1 gen, rank(d_1)=0, rank(d_1 from below)=0 → free_rank = 1
        // H_1: 1 gen, rank(d_1)=0, rank(d_2)=1 → free_rank = 0
        // H_2: 1 gen, rank(d_2)=1, no d_3 → free_rank = 0
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1.free_rank, 1);
        assert!(h0.1.torsion.is_empty());
        let h1 = h.groups.iter().find(|(d, _)| *d == 1).unwrap();
        assert_eq!(h1.1.free_rank, 0);
        let h2 = h.groups.iter().find(|(d, _)| *d == 2).unwrap();
        assert_eq!(h2.1.free_rank, 0);
    }

    #[test]
    fn homology_magma() {
        // Magma: Ob.pt (dim 0), Ob.ob (dim 1), m (dim 2).
        // m : ob ob -> ob. Output face: 1 × ob. Input face: 2 × ob.
        // d_2(m) = ob - 2*ob = -ob. Matrix [-1]. Rank 1.
        // H_0 = Z, H_1 = 0, H_2 = 0.
        let complex = load_type(&fixture("Magma.ali"), "Magma");
        let h = compute_homology(&complex);
        eprintln!("{}", h);
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1.free_rank, 1);
        let h1 = h.groups.iter().find(|(d, _)| *d == 1).unwrap();
        assert_eq!(h1.1.free_rank, 0);
    }

    #[test]
    fn homology_p2_torsion() {
        // P2 models RP²: H_0 = Z, H_1 = Z/2, H_2 = 0.
        let complex = load_type(&fixture("P2.ali"), "P2");
        let h = compute_homology(&complex);
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1, AbelianGroup { free_rank: 1, torsion: vec![] });
        let h1 = h.groups.iter().find(|(d, _)| *d == 1).unwrap();
        assert_eq!(h1.1, AbelianGroup { free_rank: 0, torsion: vec![2] });
        let h2 = h.groups.iter().find(|(d, _)| *d == 2).unwrap();
        assert_eq!(h2.1, AbelianGroup { free_rank: 0, torsion: vec![] });
    }

    #[test]
    fn homology_unit() {
        let complex = load_type(&example("EckmannHilton.ali"), "Unit");
        let h = compute_homology(&complex);
        let h0 = h.groups.iter().find(|(d, _)| *d == 0).unwrap();
        assert_eq!(h0.1.free_rank, 1);
        let h3 = h.groups.iter().find(|(d, _)| *d == 3).unwrap();
        assert_eq!(h3.1.free_rank, 2);
    }

    #[test]
    fn homology_category() {
        // Category.ali has multiple types; test Ob.
        let complex = load_type(&example("Category.ali"), "Ob");
        let h = compute_homology(&complex);
        eprintln!("Ob homology:\n{}", h);
    }
}
